const router = require("express").Router();
const userMidelewre = require("../midleweres/user-midlewere")
const adminMidewlwer = require("../midleweres/admin-midlewere")
const UserController = require("../controllers/user-controller")
const authozincationMe = require("../midleweres/authancation-me")
const pressMidlewre = require("../midleweres/press-midlewere")

router.post("/register", adminMidewlwer, UserController.Register)
router.post("/login/:id", UserController.Login)
router.post("/login", UserController.LoginMe)
router.post("/login-press", UserController.LoginByPress)
router.put("/update", userMidelewre, UserController.Update)
router.delete("/delete/:id", adminMidewlwer, UserController.Delete)
router.put("/join/:team", userMidelewre, UserController.Join)
router.put("/unjoin/:team", userMidelewre, UserController.unJoin)
router.get("/get-one/:user", userMidelewre, UserController.GetOne)
router.get("/get-my", userMidelewre, UserController.GetMy)
router.get("/get-dev", authozincationMe, UserController.GetMyPress)
router.get("/get-my/admin", adminMidewlwer, UserController.GetMy)
router.get("/get-my/press", pressMidlewre, UserController.GetMyPress)
router.put("/verification/:id", UserController.Verification)
router.post("/add-admin/:site", authozincationMe, UserController.AddAdmin)
router.get("/get-all/admin", adminMidewlwer, UserController.GetAll)
router.get("/get-all", userMidelewre, UserController.GetAll)
router.post("/sertificate", adminMidewlwer, UserController.GetSertifcate)
router.put("/block/:user", adminMidewlwer, UserController.Block)
router.patch("/logout", userMidelewre, UserController.Logout)

module.exports = router;
