import { FaUser, FaBell, FaTasks, FaTrophy, FaChartPie, FaSmile, FaLightbulb, FaUsers, FaHome, FaClipboardList, FaGlobe, FaUniversity, FaStar, FaNewspaper, FaBook } from "react-icons/fa";

export const navLinks = [
  { route: "/", name: "Bosh sahifa", icon: FaHome },
  { route: "/teams", name: "Jamoalar", icon: FaUsers },
  { route: "/tests", name: "Testlar", icon: FaClipboardList },
  { route: "/public-tests", name: "Ommaviy Testlar", icon: FaGlobe },
  { route: "/centers", name: "O'quv Markazlari", icon: FaUniversity },
  { route: "/ratings", name: "Ratinglar", icon: FaTrophy },
  { route: "/bests", name: "A'lolar", icon: FaStar },
  { route: "/news", name: "Yangiliklar", icon: FaNewspaper },
  { route: "/books", name: "Kutubxona", icon: FaBook },
];

export const userMenuLinks = [
  { route: "/profile", name: "Profil", icon: FaUser },
  { route: "/notification", name: "Bildirishnomalar", icon: FaBell },
  { route: "/my-tests", name: "Mening Testlarim", icon: FaTasks },
  { route: "/my-achive", name: "Mening Yutuqlarim", icon: FaTrophy },
  { route: "/my-statistics", name: "Mening Statistikam", icon: FaChartPie },
  { route: "/motivation", name: "O'zinga ishon!", icon: FaLightbulb },
  { route: "/happy-world", name: "Qiziqarli dunyo!", icon: FaSmile }, 
];

export const motivations =  [
  "Har kuni yangi imkoniyatlar bilan boshlanadi.",
  "Orzularing uchun kurashishdan aslo to'xtama.",
  "Sen kuchliroqsan, faqat o'zingga ishon!",
  "Har bir qadam seni orzuyingga yaqinlashtiradi.",
  "Vaqt o‘tadi, lekin natijalar qoladi.",
  "Omad jasurlarga kuladi.",
  "Hatto kichik g‘alabalar ham katta natijalarga olib keladi.",
  "Vazgechma, eng qiyin paytlar o'sish davri bo‘ladi.",
  "Bugun boshlagan ishing ertaga meva beradi.",
  "O'zingni kechagi kundan kuchliroq qil.",
  "Muvaffaqiyat sabr va mehnat natijasidir.",
  "Tushkunlikdan voz kech, oldinga qarab intil!",
  "O'z orzularing uchun kurashishga arziydi.",
  "Harakat qilgan inson doimo maqsadiga yetadi.",
  "Hayotingni o'zgartirishni bugundan boshlang.",
  "Har bir xato – bu yangi imkoniyat.",
  "Bugungi harakat kelajakdagi g‘alaba.",
  "Hech qachon taslim bo‘lma!",
  "O'zgarishni o'zingdan boshlang.",
  "Katta orzular – katta natijalar.",
  "Hech narsa imkonsiz emas.",
  "Mehnat qilgan odam doimo g‘alaba qozonadi.",
  "Bugun qilgan kichik qadamlaring ertaga katta farq qiladi.",
  "Sen ajoyib narsalarga qodirsan.",
  "Har kuni o'z ustingda ishlash — haqiqiy yutuqdir.",
  "Kuchli bo'lish — oson emas, lekin mumkin.",
  "Sabrlilik – muvaffaqiyatning kaliti.",
  "Xatolar – tajriba orttirish vositasi.",
  "Buyuk ishlar sabr va fidoyilik bilan amalga oshadi.",
  "Shunchaki harakatni davom ettir!",
  "Har safar yiqilsang, yana o‘rnidan tur!",
  "Maqsading sari qat'iy yur!",
  "To'xtamasdan orqaga qarama!",
  "O'z orzularingni hech kimdan kam ko‘rma.",
  "Mashaqqatli mehnat eng kuchli qurolingdir.",
  "Qo'rqma, qadam tashla!",
  "Hayot imkoniyatlarga to‘la — foydalan.",
  "Katta natijalar sabr bilan keladi.",
  "Bugungi mehnat ertangi orzularingni amalga oshiradi.",
  "Tushkunlik — bu vaqtinchalik to‘siq.",
  "Sen o'zingni o'zgartira olasan.",
  "Doimo oldinga intil!",
  "Ishon va harakat qil!",
  "O'ziga sodiq qol.",
  "Aql va sabr bilan harakat qil.",
  "Senga ishonadigan odamlar bor.",
  "Haqiqiy kuch ichingda.",
  "Orzularni ko‘z ochib yumguncha amalga oshirish mumkin.",
  "Xohlagan narsangga erishishing mumkin.",
  "Faoliyat — eng yaxshi motivatsiya.",
  "Katta orzular katta harakat talab qiladi.",
  "Eng yaxshisi hali oldinda.",
  "Har kungi kichik yutuqlar katta muvaffaqiyatdir.",
  "Vaqtni qadrlang, har bir daqiqa muhim.",
  "Omadsizlik – muvaffaqiyatning boshlanishi.",
  "Shaxsiy o‘sish — eng katta boylik.",
  "O'zingga sodiq qol va harakatni davom ettir.",
  "Sabr qilgan g‘olib bo‘ladi.",
  "Sen o‘z orzularing me'morisan.",
  "Hayotingni faqat o‘zing o‘zgartirishing mumkin.",
  "Ishonch — kuchning asosi.",
  "Bugun boshlagan ishing, kelajakda sening boyliging bo‘ladi.",
  "Muvaffaqiyatli odam hech qachon taslim bo‘lmaydi.",
  "Bir qadam ham natija beradi.",
  "Qiyinchiliklar seni kuchliroq qiladi.",
  "Harakat qil, orqaga qaram.",
  "Ko'proq harakat, kamroq bahona.",
  "Sen istagan hayot o'zingning qo'lingda.",
  "Chegaralar faqat ongimizda mavjud.",
  "O'z orzularingni sev!",
  "Bugun qilingan mehnat, ertangi natijani belgilaydi.",
  "Sen chinakam yulduzsan.",
  "G‘alaba jasurlarga nasib qiladi.",
  "Muvaffaqiyat harakat bilan do‘st.",
  "O'zingga va orzularingga sodiq qol.",
  "Harakat – orzularni ro‘yobga chiqarishning kaliti.",
  "Sen boshlamasang, hech narsa o‘zgarmaz.",
  "Yaxshi niyat, sabr va harakat bilan hamma narsa mumkin.",
  "Muvaffaqiyatga intilishdan aslo to'xtama.",
  "Bugun qilgan harakatlaring kelajakdagi hayotingni belgilaydi.",
  "Orzularni ro'yobga chiqarish uchun bir qadam tashla.",
  "Ajoyib narsalar sabr va mehnat bilan yaratiladi.",
  "Kechikkan payting ham hali kech emas.",
  "Xatolardan qo‘rqma, ulardan o‘rgan.",
  "Sen har kuni yaxshiroq bo‘la olasan.",
  "O'zingni rivojlantirish – eng katta investitsiya.",
  "Sen uchun imkonsiz narsa yo'q.",
  "Har bir kun yangi imkoniyatdir.",
  "Orzularingni o‘z qadaming bilan amalga oshir.",
  "Harakat qilishni to‘xtatma.",
  "Sabr va mehnat seni yuqoriga olib chiqadi.",
  "Sen ko‘proq narsaga qodirsan, ishon!",
  "Bugun sening kuning!",
  "Hayotda eng katta yutuq – o‘z orzularingni amalga oshirishdir.",
  "Faol bo‘l, natijani kut.",
  "Kichik qadamlar katta o'zgarishlar keltiradi.",
  "Har kuni kichik bir qadam tashla.",
  "Sen o‘z hayotingning qahramonisan.",
  "Vazgechish oson, lekin davom etish qahramonlikdir.",
  "Haqiqiy g'alaba — o'z ustingda g‘alaba qozonishdir.",
  "Harakat qil, taslim bo‘lma!",
  "Har bir mag'lubiyat – yangi imkoniyat.",
  "G‘alaba senga yaqinroqdir, qadam tashla!",
  "To'xtama, intil!",
  "Sen o‘z qahramoning.",
  "Bugun boshlash – ertangi g‘alaba sari qadam.",
  "Sen kuchlisan, bunga ishon!",
  "Orzularing sari hech to‘xtamay intil.",
  "Imkonsiz narsa yo‘q!",
  "Haqiqiy kuch ichingda yashiringan.",
  "Hayotingni o‘zgartirish uchun bitta qadam tashla.",
  "Kuchli bo‘l, sabrli bo‘l.",
  "Har kuni yaxshilanishga harakat qil.",
  "Harakat — muvaffaqiyatning kaliti.",
  "Bugun eng yaxshi kuning!",
  "Qiyinchiliklar seni kuchliroq qiladi.",
  "Sabr va matonat — eng yaxshi do‘stlaring.",
  "Orzularingni asla unutma.",
  "Harakat qil, orzularing seniki bo‘ladi.",
  "Sen eng yaxshilarga loyiqsan!",
  "Muvaffaqiyat mehnatsiz kelmaydi.",
  "Kuchli orzular kuchli harakatni talab qiladi.",
  "Harakat — kelajakdagi yutuqning boshlanishi.",
  "Bugun qilgan harakatlaring ertaga samara beradi.",
  "Sabrli bo‘l, natijani kut.",
  "Hayoting senga tegishli!",
  "Har kuni yaxshiroq bo‘lishga intil.",
  "Ishonch bilan qadam tashla!",
  "O‘z yo‘lingda davom et!",
  "Tushkunlik – vaqtinchalik, kuch esa abadiy.",
  "Orqaga qarama – faqat oldinga!",
  "Har kuni motivatsiya bilan boshlang.",
  "Katta g‘alabalar kichik qadamlar bilan boshlanadi.",
  "Xatolar – o‘rganish vositasi.",
  "Sen mumkin bo‘lmagan narsani ham uddalay olasan.",
  "Orzular orqasidan quvishga arziydi.",
  "Hech qachon taslim bo‘lma!",
  "Sen o‘zingni ajoyib kelajaging yaratuvchisan.",
  "Bugun boshlash — eng yaxshi qaror.",
  "Har bir qiyinchilik — yangi imkoniyat.",
  "O'z orzularingni sev!",
  "O'zingga vaqt ajrat, o'zingni rivojlantir!",
  "Sen ulug'vor ishlarga loyiqsan.",
  "Mehnat qil, sabr qil va ishon!",
  "Doimo oldinga yur!",
  "Hayot senga imkoniyatlar beradi.",
  "Bugun qilingan kichik harakatlar katta g‘alabalarni olib keladi.",
  "O'zingni kam baholama.",
  "Sen o‘z imkoniyatlaringni kashf et.",
  "Muvaffaqiyat senga yaqin.",
  "Sen o‘zingdan kuchliroqsan.",
  "Ishonch — eng katta kuchdir.",
  "Orzularingni amalga oshiradigan kuch sendadir."
]

export const facts = [
  "Atlantik okeanining tubida 1912-yilda cho'kkan Titanic kemasi hali ham yotibdi.",
  "Dunyoning eng tez hayvonlari gepardlar soatiga 120 km tezlikka erisha oladi.",
  "Baliqlarning ba'zilari suvdan tashqariga sakrab yurishga qodir.",
  "Dunyoda 7000 dan ortiq tillar mavjud.",
  "Koalalar kuniga 22 soat uxlaydi.",
  "Inson miyasi sekundiga 1 kvadrillion amalni bajarishga qodir.",
  "Pingvinlar bir umrga bitta juftni tanlaydi.",
  "Mars sayyorasida quyosh botishi ko'k rangda bo'ladi.",
  "O'rta Yoshdagi kattalar tanasining 60% suyuqlikdan iborat.",
  "Oktyabr oyida Antarktida ustida eng katta ozon teshigi aniqlangan.",
  "Dunyoda har yili 1,3 milliard tonna ovqat isrof bo'ladi.",
  "Yupiter sayyorasining diametri 139,820 km ga teng, bu yer sharining 11 baravaridan kattaroq.",
  "Oq ayiqlar qorli hududlarda yashaydigan eng katta yirtqich hayvonlardir.",
  "Kichik ko'rinishga ega bo'lgan gemoroylar aslida 40 smgacha katta bo'lishi mumkin.",
  "Himalay tog'larining tepasida ba'zi o'simliklar juda kam vaqt ichida 15 smga qadar o'sib ulgura oladi.",
  "Venus sayyorasi yerga qaraganda 30% ko'proq issiqlikni saqlaydi.",
  "Dunyodagi eng qadimiy daraxt — 5,000 yoshli Pinus longaeva.",
  "Ba'zi qushlar, xususan, kalakaning turlaridan ba'zilari, 2.5 km balandlikka uchishi mumkin.",
  "Toshbaqalar suvlarda soatlab yoki kunlab yashashga qodir.",
  "Japoniyada yer yuzida ko'plab issiq suv manbalari bor.",
  "Ayrim odamlar nafas olishda xato qilishadi, ya'ni havoni ko'p miqdorda yutishadi.",
  "Olimpik o'yinlar 776 yil miloddan avval Gretsiyada boshlangan.",
  "Inson tanasida har bir soch folikulasidan 2-3 qism o'sadi.",
  "Yulduzlar quyuq, ammo muzlanuvchi gazlardan tashkil topgan.",
  "Sovuq joylarda hayvonlar ko'pincha rangli jun yoki pardalar bilan yopilgan bo'ladi.",
  "Okeanlar inson tanasidan 3000 marta kattaroq.",
  "Dunyoda 180 ta davlat bor.",
  "Barcha qushlar ularning qanotlari bilan uchishadi.",
  "Havoning haroratini aniqlash uchun harorat skalyasining aniqligi juda muhimdir.",
  "Ba'zi yirik kitlar shunchaki dengizda mavjud bo'lishi mumkin.",
  "Yevropada deyarli 2 milliondan ortiq hayvonlar turi mavjud.",
  "Baliqlarning ba'zilari shunchaki muzlatilgan holda yashashadi.",
  "Insonning rivojlanishiga ijobiy ta'sir ko'rsatadigan hayvonlar turli xil vazifalarni bajarishga qodir.",
  "Ushbu mavzuda yirik hayvonlarning rangli turli xil ranglar bilan mavjudligi mashhur.",
  "Baliqlar suvda qutqaruvchi mexanizmlardan foydalanib hayotlarini davom ettiradilar.",
  "Dunyoning haroratli o'simliklari o'zlariga tegishli hayvonlar bilan yashashadi.",
  "Yovvoyi yirtqichlar ko'pincha o'zlarini osongina uyda ushlab qolishga qodir.",
  "Dunyodagi eng katta hayvonni qidirish o'zgaruvchan.",
  "Ba'zi odamlar uchun ba'zi joylardagi o'simliklarning tasvirlari muhimdir.",
  "Jismoniy sog'liqning yuksalishi turli xil o'zgarishlarga olib keladi.",
  "Ba'zi odamlar suvda hayotlarni uzoq davom ettiradilar.",
  "Tovuq tuxumlari va boshqa mahsulotlar to'liq o'sishi mumkin.",
  "Ko'plab hayvonlar bugungi kunda sayyorada yashashda ham davom etmoqda.",
  "Dunyodagi eng katta o'simliklarni qidirish davom etmoqda.",
  "Hayvonlarning turli xil qiyinchiliklar yuzasidan yashash ehtiyojlari mavjud.",
  "Yuqori darajadagi mashaqqatli hayvonlar bilan yashashdagi muammolar mavjud.",
  "Hayvonlarning o'zgaruvchanligini o'rganish kerak.",
  "Har doim hayvonlar yaxshi muomala qilinishiga e'tibor qaratish kerak.",
  "Yevropada hayvonlar yoki o'simliklar yetishtirilgan maydonlar mavjud.",
  "Hayvonlar o'zgaruvchan muhitda yashash ehtiyojlarini yaxshi tushunadilar.",
  "Gullarning ko'plab turlari o'zlarini yaxshi hayotga olib borishga yordam beradi.",
  "Ba'zi hayvonlar o'z vaqtida bir xil ranglarda o'zgarishi mumkin.",
  "Suvda yashashni xohlaydigan ba'zi o'simliklar turli xil bo'lishi mumkin.",
  "Ba'zi hayvonlar mavjudligi juda oz va oddiy joylar uchun ko'rinadi.",
  "Ba'zi hayvonlar o'z hayotini o'zgartirishga tayyorlar.",
  "Ba'zi hayvonlarning mavjudligi, odamlar uchun juda foydali.",
  "Ba'zi hayvonlar xuddi shu o'zgaruvchan sharoitlarda yashashni davom ettiradilar.",
  "O'simliklarning hayot uchun muhim ekanligi, ba'zi joylarda mavjudligi bilinar.",
  "Hayvonlar orqali tizimlar ko'plab muammolarni hal qilishga qodir.",
  "Hayvonlarning tajribalari, odamlarning sog'lig'ini yaxshilashga yordam beradi.",
  "Ko'plab odamlar hayotda ba'zan ba'zi joylarda yoki biron bir davrda o'zlarini qoniqarli his qilmaydi.",
  "Ba'zi hayvonlar qish oylarida o'zgaruvchan iqlimga moslashadi.",
  "Odamlar uchun eng yaxshi o'simliklar ko'pincha issiq joylar va pastki qismga qarab o'sadi.",
  "Ba'zi hayvonlar yillar davomida faqat bir nechta o'zgarishlarga ega.",
  "Hayvonlarning yaxshi boshqaruv tizimlari o'zgaruvchan bo'lishi mumkin.",
  "Dunyo bo'ylab yashovchi yirik hayvonlar turlarini o'rganish muhimdir.",
  "Ba'zi hayvonlar turli xil vaqtlarda o'z hayotlarida kichik o'zgarishlarni amalga oshiradi.",
  "Ko'plab odamlar kuchli tuyg'ular bilan o'zgarishlarni tezda boshdan kechiradilar.",
  "Dunyoda ba'zi hayvonlar yangi o'simliklarni tanlash va o'stirish uchun harakat qilishadi.",
  "Ba'zi hayvonlar quyuq suvlarda turli xil o'simliklar o'sishi mumkin.",
  "Hayvonlarning aqli va jismoniy salohiyati ba'zan o'zgaradi.",
  "Tuzli suvda turadigan ba'zi hayvonlar o'zlarini ko'proq qulay his qilishadi.",
  "Odamlar ba'zan tabiatda yashash uchun moslashishlari kerak.",
  "Suvda yashovchi hayvonlar o'z vaqtida harakat qilishga tayyor.",
  "Ba'zi o'simliklar, odamlar uchun har xil foydali xususiyatlarga ega.",
  "Ba'zi hayvonlar o'z vaqtida shaxsiy farovonlikni yaratishga qodir.",
  "Odamlar o'zlarining muvaffaqiyatli rivojlanishlariga doimo intilishlari kerak.",
  "Hayvonlar o'zgaruvchan va ba'zan kuchli muhitda yashashga qodir.",
  "Ba'zi hayvonlar o'zgaruvchan vaziyatda o'zlarini yaxshi his qiladilar.",
  "Hayvonlarning o'zaro aloqalari va munosabatlari odamlarning harakati bilan muhimdir.",
  "Odamlar ba'zida o'zlarini yaxshi tushunishga harakat qilishlari kerak.",
  "Ba'zi hayvonlar juda uzoq davom etadigan stress holatlariga toqat qilishadi.",
  "Hayvonlar tabiatda o'zgaruvchan dunyoda yashashga intilishadi.",
  "Yirik o'simliklar ba'zan turli xil joylarda o'zgarishi mumkin.",
  "Hayvonlar turli joylarda yashashni davom ettirishi mumkin.",
  "Hayvonlar yaxshi hayot uchun turli xil yangi imkoniyatlarni o'rganadilar.",
  "Odamlar o'zgarishlarni o'z vaqtida boshdan kechirishlari kerak.",
  "Ba'zi hayvonlar o'zlarining muhitini o'zgartirishni davom ettiradilar.",
  "Ko'plab o'simliklar va hayvonlar o'zgaruvchan muhitda yashash uchun moslashadi.",
  "Odamlar ko'pincha o'zlarining ishlarida o'zgarishlarni ko'rishadi.",
  "Dunyo bo'ylab hayvonlarning va o'simliklarning ko'plab turlari mavjud.",
  "Ba'zi hayvonlar o'zlarini yaxshi yashashga tayyorlaydi.",
  "Hayvonlar o'zgaruvchan va muhim vazifalarni bajarish uchun harakat qilishadi.",
  "Ko'plab odamlar o'zlarining hayotida ba'zi o'zgarishlarga ega.",
  "Dunyoda ba'zi hayvonlar o'zlarini himoya qilish uchun turli xil usullarni ishlatadilar.",
  "Yirik o'simliklar, odamlar uchun ko'plab foydali xususiyatlarga ega.",
  "Ko'plab hayvonlar o'zlarini yaxshi rivojlantirish uchun turli xil usullarni sinovdan o'tkazadilar.",
  "Dunyoda ko'plab hayvonlar turli xil sharoitlarga moslashgan.",
  "Odamlar o'zlarini ba'zida yangi muhitlarga moslashtirishlari kerak.",
  "Yirik hayvonlar, ba'zan o'zgarishlarni tezda sezadilar.",
  "Ba'zi hayvonlar turli xil joylarga moslashishga qodir.",
  "Ba'zi hayvonlar ba'zi o'simliklar bilan bog'lanadi.",
  "Ko'plab hayvonlar turli muhitlarda yashashga tayyor.",
  "Ba'zi hayvonlar har xil tabiiy resurslardan foydalanadilar.",
  "Odamlar ba'zan o'zlarini o'zgarishlarga tayyorlashlari kerak.",
  "Ba'zi hayvonlar, o'zgaruvchan dunyoda o'zlariga moslashishni o'rganadi.",
  "Hayvonlar tabiiy muhitda o'zgarishlarga moslashishlari kerak.",
  "Ba'zi hayvonlar har xil sharoitlarda yaxshi yashashga tayyor.",
  "Ba'zi o'simliklar ba'zi hayvonlar bilan yashaydi.",
  "Hayvonlar o'zlarini o'zgarishlarga tayyorlaydi.",
  "Ba'zi hayvonlar o'zgaruvchan muhitda yangi imkoniyatlarni o'rganishga tayyor.",
  "Yirik hayvonlar va o'simliklar turli xil muhitlarda yashashni davom ettiradilar.",
  "Dunyodagi eng katta cho'l, Sahara cho'li, 9,2 million kvadrat kilometrni tashkil etadi.",
  "Qushlar yer yuzasida eng engil jonivorlardir.",
  "O'rmonlar dunyodagi kislorodning 30% ini ishlab chiqaradi.",
  "Odamlarning 90% dan ortig'i o'zlarini yaxshi his qilish uchun tabiatga chiqishni afzal ko'radi.",
  "Ba'zi yirik baliqlarning yuragi odamlarining to'liq tana hajmiga teng bo'lishi mumkin.",
  "Yupiterning atmosferasi Nyu-York shahrining 11,000 km kenglikka teng bo'lib, olamdagi eng katta bulutlar tizimi.",
  "Baliqning aksariyati boshqa hayvonlar bilan solishtirganda aqlan yuqori bo'lishi mumkin.",
  "Dunyodagi eng katta vulkanni Yupiterdagi Io oyida ko'rish mumkin.",
  "Odamlar o'z fikrlarini boshqalar bilan oson bo'lganda aniqroq ifodalaydilar.",
  "Baliqlar, ba'zan o'zlarining ko'rinishlarini o'zgartirish qobiliyatiga ega.",
  "Suvda yashovchi hayvonlar har xil ko'rinishda va turli xil xususiyatlarga ega.",
  "Ba'zi yirik baliqlar 30 metr yoki undan ko'p uzunlikka erisha oladi.",
  "Odamlar ba'zan o'zlariga muhim va kerakli bilimlarni o'rganish uchun tabiiy muhiti bilan bog'lanadilar.",
  "Ba'zi odamlar o'zlarini tabiatda yashashga tayyorlaydilar.",
  "Ba'zi odamlar tabiat bilan yaxshi aloqa o'rnatishni afzal ko'radilar.",
  "Odamlar o'zlarining rivojlanishiga yordam beradigan yangi imkoniyatlar yaratishga tayyor.",
  "Hayvonlarning o'zgarishlarga bo'lgan javoblari turli xil va qiyinchiliklarga qarshi turadi.",
  "Ba'zi o'simliklar, hayvonlar uchun xavf tug'dirishi mumkin.",
  "Dunyo bo'ylab yashovchi hayvonlarning turli xil turlari mavjud.",
  "Odamlar o'zlarini yaxshi yashashga qaratilgan o'zgarishlarga tayyorlashlari kerak.",
  "Dunyoda ba'zi o'simliklar yangi imkoniyatlarni o'rganishga tayyor.",
  "Ba'zi hayvonlar tabiiy muhitda o'zgarishlarni o'z vaqtida boshdan kechiradi.",
  "Odamlar o'zlarini o'zgarishlarga tayyorlashga qodir.",
  "Hayvonlar o'zlarining aqliy salohiyatlarini yuqori darajaga ko'tarishga intilishadi.",
  "Ba'zi hayvonlar o'zlarini yangi sharoitlarga tayyorlashga harakat qilishadi.",
  "Ba'zi hayvonlar har xil yangi imkoniyatlarni izlashadi.",
  "Odamlar yangi imkoniyatlarni o'rganishga tayyorlanishlari kerak.",
  "Dunyo bo'ylab turli xil hayvonlar o'zlarini yangi muhitlarga moslashishga tayyor.",
  "Yirik hayvonlar yangi imkoniyatlarni topishga qodir.",
  "Ba'zi hayvonlar yangi xususiyatlarga ega bo'lishi mumkin.",
  "Odamlar o'zlarini turli xil muhitlarga moslashtirishga tayyorlashlari kerak.",
  "Ba'zi hayvonlar tabiatda o'zgarishlarga toqat qilishadi.",
  "Dunyoda hayvonlar va o'simliklarning ko'plab turlari mavjud.",
  "Ba'zi hayvonlar o'zgaruvchan vaqtlarda o'zlarini yaxshi his qilishadi.",
  "Hayvonlar turli xil muhitlarda yashashga qodir.",
  "Dunyo bo'ylab hayvonlar o'zlarini yangi imkoniyatlarga moslashtirishga tayyor.",
  "Dunyodagi ba'zi hayvonlar turli xil o'simliklarni iste'mol qilishadi.",
  "Ba'zi hayvonlar yangi sharoitlarda o'zlarini yaxshi his qilishadi.",
  "Odamlar o'zgarishlarni yaxshi boshqarish uchun tabiiy muhitda yashashga tayyorlashlari kerak.",
  "Ba'zi hayvonlar har xil sharoitlarda o'zgarishlarni sezadilar.",
  "Ba'zi hayvonlar o'zgaruvchan vaqtlarda o'zlarini yaxshi rivojlantiradilar.",
  "Odamlar tabiatda yashashni afzal ko'radilar.",
  "Yirik hayvonlar o'zgaruvchan vaqtlarda yaxshi yashashga qodir.",
  "Dunyoda ba'zi hayvonlar tabiatda yashashga o'zgarishlarni o'rganishadi.",
  "Ba'zi hayvonlar yangi imkoniyatlarni izlashadi.",
  "Ko'plab hayvonlar yangi imkoniyatlarga moslashishga tayyor.",
  "Ba'zi hayvonlar o'zlarini yangi imkoniyatlarga tayyorlashga qodir.",
  "Odamlar tabiat bilan bog'lanishni davom ettirishlari kerak.",
  "Ba'zi hayvonlar o'zgaruvchan dunyoda yaxshi yashashga qodir.",
  "Odamlar yangi imkoniyatlarga moslashishga tayyorlar.",
  "Dunyodagi ba'zi hayvonlar yangi imkoniyatlarni izlashadi.",
  "Ba'zi hayvonlar yangi xususiyatlarga ega.",
  "Ba'zi hayvonlar har xil muhitlarda yashashga tayyor.",
  "Dunyodagi eng qiziqarli hayvonlar turli xil sharoitlarda yashaydi.",
  "Odamlar o'zlarini o'zgarishlarga tayyorlashga qodir.",
  "Ba'zi hayvonlar o'zgaruvchan vaqtlarda o'zlarini yaxshi rivojlantiradilar.",
  "Ba'zi hayvonlar tabiatda yashashga tayyor.",
  "Odamlar o'zgarishlarga tayyorlanishlari kerak.",
  "Ba'zi hayvonlar turli xil o'simliklar va hayvonlar bilan yashaydi.",
  "Odamlar o'zgarishlarga tayyorlashga qodir.",
  "Dunyodagi ba'zi hayvonlar yangi imkoniyatlarga moslashishga tayyor."
]


  